Vagrant.configure("2") do |config|
    config.vm.box = "steelbox-1.0.0"

    config.vm.host_name = "{{ cookiecutter.repo_name }}.vm"
    config.vm.network :private_network, ip: "10.10.10.{{ cookiecutter.port }}"
    config.vm.synced_folder ".", "/home/vagrant/{{ cookiecutter.repo_name }}", type: "nfs"
    config.vm.provision "shell", inline: <<-SCRIPT
        sudo -su postgres createdb --template=template0 --encoding='UTF-8' --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8' {{ cookiecutter.repo_name }}
    SCRIPT

    config.vm.provider "virtualbox" do |vb, override|
        override.vm.box_url = "https://s3-eu-west-1.amazonaws.com/steelseries-vagrant-boxes/steelbox-1.1.0.box"
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
end
